title: Siddhartha Sharma
logo: "/images/Siddhartha_Sharma.jpg?raw=true" # your photo (or logo) here
description: > Official Portfolio
  Hey there fellow coders! 
  <br><br>
  I'm currently a student passionate about Artificial Intelligence and Machine Learning, working everyday to hone my skills in the respected field.
  <br><br>
  <a href="https://www.linkedin.com/in/siddhartha-sharma-105b03202/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
